ktor:
    application:
        modules:
            - org.ktorite.ApplicationKt.module
    deployment:
        port: 8080
        shutdown:
          url: "/shutdown"
postgres:
  url: "jdbc:postgresql://localhost/default"
  user: username
  password: "passwordjwt"
  domain: "https://jwt-provider-domain/"
  audience: "jwt-audience"
  realm: "ktor sample app"
